### ISSUE TITLE
More than one CSV files in entity is being empty of data

### ISSUE THREAD

**Issue by Bertverbeek4PS** [microsoft/bc2adls#11]
I have runned the bc2adls tool in combination with Data Archive functionality (with some changes).
The exported files looked very good. The pipelines are running (Consolidation_AllEntities).
But there is no consolution data in the folder data. Only the headers.

1. I have removed all the files in my Azure Data Lak
2. Export te data to Azure Data Lake from BC:
[Before_pipeline.zip](https://github.com/microsoft/bc2adls/files/7933616/Before_pipeline.zip)
e
3. Run the pipeline Consolidation_AllEntities
4. All the files in data folder have only headers and no data.
[After_pipeline.zip](https://github.com/microsoft/bc2adls/files/7933730/After_pipeline.zip)
[Code.zip](https://github.com/microsoft/bc2adls/files/7933732/Code.zip)

Also this is the code change I have done:

**Comment by DuttaSoumya** [comment]
First of all thanks a lot @Bertverbeek4PS for using this tool! Indeed the integration with [the Data Archiving functionality](https://docs.microsoft.com/en-au/dynamics365/business-central/admin-archive-data) is a great idea and perhaps useful for many other users as well.

When I looked at the files, I noticed that the following meta data columns are missing in the CSV file in Before_pipeline.zip. 
`timestamp-0,systemId-2000000000,SystemCreatedAt-2000000001,SystemCreatedBy-2000000002,SystemModifiedAt-2000000003,SystemModifiedBy-2000000004`

These columns are essential for the Synapse pipeline to execute properly.

For this reason I shall be closing this issue for now.
