### ISSUE TITLE
Transition to Azure Synapse runtime for Apache Spark 3.2 or 3.3 

### ISSUE THREAD

**Issue by tglink72** [microsoft/bc2adls#115]
All,

     Hello and hope all is well. We received a notification from Microsoft that the Synapse workloads we use for the BC2ADL tool are referencing a version of the Azure Synapse runtime for Apache Spark that will expire in September. While we do not use this functionality within our process, I believe we will need to update the references in the pipelines. Is there a current resolution to this in an existing version of the BC2ADL tool? Or is this issue being reviewed by the team?

 Below is the notification.

Thanks

Tom Link

Transition to Azure Synapse runtime for Apache Spark 3.2 or 3.3 
You're receiving this notice because you have workloads that use Azure Synapse runtime for Apache Spark 2.4 between April 12, 2023, and May 12, 2023.
On 29 September 2023, Azure Synapse runtime for Apache Spark 2.4 will be retired in accordance with the [Synapse runtime for Apache Spark lifecycle policy](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fazure%2Fsynapse-analytics%2Fspark%2Fruntime-for-apache-spark-lifecycle-and-supportability&data=05%7C01%7Ctom.link%40stoneridgesoftware.com%7C212ee37c597d4c31ca4108db56065ac2%7C2e14a5b1fbf8415bbc7d93e20829e510%7C1%7C0%7C638198357540621514%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Iaj3ZRclc7Xv16KP5rofidiz0PhUqtNtM7fQzAtZI1w%3D&reserved=0), and any workloads still using it will stop running. Before that date, you'll need to transition your workloads to version 3.2 or 3.3.

**Comment by DuttaSoumya** [comment]
Hi Tom (@tglink72),

Thanks for letting us know. Could you please try the following to get rid of this message,
* Refresh your setup of the shared metadata tables by following the instructions [here](https://github.com/microsoft/bc2adls/blob/80abc7eaf3493c25e1fb7695953ad4dd3fd7c55c/.assets/SharedMetadataTables.md).
* If that does not help, could you please refresh the setup of your Synapse workspace, or better still create a new one.

Best regards,
Dutta
CSA, Microsoft.

**Comment by DuttaSoumya** [comment]
Closing this out as it has been 2 weeks.
