### ISSUE TITLE
Every file exported file is in CSV

### ISSUE THREAD

**Issue by EBGUser** [microsoft/bc2adls#117]
Hello,

I have an Issue with the type of file exported. Every time I export, the file created is in CSV, even when I ask to put it in parquet.

I try to delete all the file, modify the json file with pasting the parquet mode and even deleted the CSV option in all the code but each time it doesn't work.

And when I try to debug it doesn't use or ask which type of file I want. 
I think all of this is created by an API and force it to be in a csv type.

Thank you,
Philippe

**Comment by DuttaSoumya** [comment]
Hello @EBGUser 

Please take a look at the following 
![image](https://github.com/microsoft/bc2adls/assets/38040179/5ad5cf5e-f8f7-4dad-b788-39534cde6d49)
Ref: https://github.com/microsoft/bc2adls/blob/main/.assets/Setup.md#configuring-the-dynamics-365-business-central

Best regards,
Soumya Dutta
CSA, Microsoft.

**Comment by DuttaSoumya** [comment]
Closing the thread as the explanation above is hopefully sufficient.
