### ISSUE TITLE
Add Folder path option for container

### ISSUE THREAD

**Issue by j-heinze** [microsoft/bc2adls#119]
Hello,

is it possible to add an optional directory path to further determine the export location for the data? 

Currently only the container can be specified:
![image](https://github.com/microsoft/bc2adls/assets/29870416/e1fca542-b36b-4aae-9288-c4d4085611ff)

Thank you,
Jan

**Comment by DuttaSoumya** [comment]
Hi @j-heinze ,

I am keen to understand the necessity for this requirement and which use case it originates from. It should be fairly easy to create your own container with naming convention defining its purpose, say

- `landingzone-bc`
- `landingzone-dataverse`
- `landingzone-crm`
- . . .

Best regards,
Dutta.

**Comment by j-heinze** [comment]
Hi @DuttaSoumya,
I understand the thought behind this. It's just that we already have an existing datalake which is structured like the following:

- Container landingzone
  - Directory Source=BC
  - Directory Source=CRM
- Container bronze
  - Directory Source=BC
  - Directory Source=CRM
- Container silver
...

This would allow us to integrate it in the existing structure. In general, why would it not make sense to fully specify a path for the export? Of course it would require an additional parameter for the pipelines and dataflow/notebook.

Best regards,
Jan

**Comment by DuttaSoumya** [comment]
Assuming that there are no further comments on this since last 9 days, will close issue.
