### ISSUE TITLE
Is there a way to configure double quote escaping in delta .csv files 

### ISSUE THREAD

**Issue by Isarien** [microsoft/bc2adls#125]
Hello,

I've read the documentation, but couldn't find a way to change the double quote escape for delta .csv files.
Can you tell me if it is configurable?

**Comment by DuttaSoumya** [comment]
Have you looked at the procedure `UpdateDefaultManifestContent` in [ADLSECDMUtil](https://github.com/microsoft/bc2adls/blob/main/businessCentral/src/ADLSECDMUtil.Codeunit.al) codeunit?

**Comment by Isarien** [comment]
> Have you looked at the procedure `UpdateDefaultManifestContent` in [ADLSECDMUtil](https://github.com/microsoft/bc2adls/blob/main/businessCentral/src/ADLSECDMUtil.Codeunit.al) codeunit?

Hello @DuttaSoumya. 
Thank you for your answer.
No, I didn't look in the code. It seems to match. On the other hand, I have the impression that it requires modifying the code. I will see with the integrator who configures the export to see if he can act on this part of the configuration

**Comment by DuttaSoumya** [comment]
Closing the thread.
