### ISSUE TITLE
Incorrectly escaping double quote

### ISSUE THREAD

**Issue by trimline-gaiustemple** [microsoft/bc2adls#19]
Hello,
It seems that double quotes are being escaped incorrectly
E.g. if a business central customer name is
`Test customer "Test"`
it becomes
`"\"Test customer \"Test\"\""`

This stackoverflow link describes escaping double quotes in csv
https://stackoverflow.com/questions/17808511/properly-escape-a-double-quote-in-csv

**Comment by pri-kise** [comment]
I guess this is the current implementation..?
https://github.com/microsoft/bc2adls/blob/fe230a2d4c5137ffafb8c7c3ed0fcb64aa03d276/businessCentral/src/ADLSEUtil.Codeunit.al#L213
There is no specific escaping as far as I can see.

**Comment by HenriSchulte-MS** [comment]
Thank you for pointing this out. We are currently reviewing and overhauling the entire escaping strategy. How we handle escaping special characters is defined in BC, the CDM metadata, and the Synapse pipelines. We are testing different strategies for unifying all of these (with a focus on making the resulting data format compatible with, e.g., Power BI and Serverless SQL).

**Comment by trimline-gaiustemple** [comment]
Great, sounds good thanks.

**Comment by HenriSchulte-MS** [comment]
We are now escaping special characters in BC and using parquet as the default storage format for CDM data in the lake. This resolves issues with quoting or escape characters in the original input.
