### ISSUE TITLE
Consolidation Pipelines Optimization

### ISSUE THREAD

**Issue by izhdanov1988** [microsoft/bc2adls#25]
Hello BC2ADLS project team, we've implemented this solution for a couple of our clients and it is working very well, thank you for your effort. It's been a few weeks of running it and now we are in the optimization stage. What we are seeing is that the run time on the synapse consolidation pipelines is increasing as we are adding more and more entities(tables) to the architecture. We were wondering if you can take a look with us, at one of the environments that we have set up and help us think about ways to optimize the run time. Right now the complete consolidation process takes 5hr for one of clients and we are trying to see if there is room for improvement. Thanks, once again!

**Comment by HenriSchulte-MS** [comment]
Hi, please reach out to us at bc2adls@microsoft.com and we can have a look!
