### ISSUE TITLE
Failing Table Export After BC Upgrade and Extension Install

### ISSUE THREAD

**Issue by tglink72** [microsoft/bc2adls#32]
Hello,

     We are exporting 29 tables from BC. After BC was upgraded over the weekend, we had to re-install the extension. Most of the tables continue to export cleanly. 1 table (Customer-18) is failing with the error below. I have tried resetting the table, I have removed it entirely from the export, re-added and re-selected columns and it continues to fail. It seems to be failing at different times in the export. I have seen file sizes in the delta of 44mb, 55mb and 179mb prior to it failing. Prior to the upgrade the full delta file was close to 700mb. Thanks for any help.

The operation was canceled. "ADLSE HttpSSI"(CodeUnit 66059).InvokeRestApi - BC2ADLS by Stoneridge Software, LLC
"ADLSE HttpSSI"(CodeUnit 66059).InvokeRestApi line 4 - BC2ADLS by Stoneridge Software, LLC
"ADLSE Gen 2 UtilSSI"(CodeUnit 66058).AddBlockToDataBlob line 13 - BC2ADLS by Stoneridge Software, LLC
"ADLSE CommunicationSSI"(CodeUnit 66054).FlushPayload line 16 - BC2ADLS by Stoneridge Software, LLC
"ADLSE CommunicationSSI"(CodeUnit 66054).CollectAndSendRecord line 14 - BC2ADLS by Stoneridge Software, LLC
"ADLSE CommunicationSSI"(CodeUnit 66054).TryCollectAndSendRecord line 3 - BC2ADLS by Stoneridge Software, LLC
"ADLSE ExecuteSSI"(CodeUnit 66056).ExportTableUpdates line 27 - BC2ADLS by Stoneridge Software, LLC
"ADLSE ExecuteSSI"(CodeUnit 66056).TryExportTableData line 12 - BC2ADLS by Stoneridge Software, LLC
"ADLSE ExecuteSSI"(CodeUnit 66056).OnRun(Trigger) line 44 - BC2ADLS by Stoneridge Software, LLC
"ADLSE ExecuteSSI"(CodeUnit 66056).ExportTableUpdates line 31 - BC2ADLS by Stoneridge Software, LLC\"ADLSE ExecuteSSI"(CodeUnit 66056).TryExportTableData line 12 - BC2ADLS by Stoneridge Software, LLC\"ADLSE ExecuteSSI"(CodeUnit 66056).OnRun(Trigger) line 44 - BC2ADLS by Stoneridge Software, LLC\

Tom

**Comment by tglink72** [comment]
Hello,

     Hope all is well. Today we tried updating the extension to the latest version posted here  and the error on the Customer export persists. Is this site still being actively monitored for issues? I have tried emailing bc2adls@microsoft.com without response also. Thanks in advance for a response.

Tom

**Comment by DuttaSoumya** [comment]
Dear Tom,

Let me sync up with you separately to understand the issue here.

Best regards,
Dutta.

**Comment by tglink72** [comment]
Soumya, Thanks for your time on the call. We upped the Max Payload Size and have not seen the issue since we met. It looks to have been a server resource\timeout issue in the export of the Customer table. Thanks again for your help!

Tom

**Comment by tglink72** [comment]
Soumya,

               Great to hear from you. Thanks for the reply.  I am working on this issue from 8-9am central time US tomorrow morning. Any chance you could join a meeting at that time?

Thanks

Tom Link
