### ISSUE TITLE
Azure Blob Storage error about Permissions mismatch

### ISSUE THREAD

**Issue by PaulFurlet** [microsoft/bc2adls#34]
Hello.
Getting in BC the error AuthorizationFailure (This request is not authorized to perform this operation.) upon attempt to CreateContainer.
But the real error is on step back - during running ContainerExists, that fails with the AuthorizationPermissionMismatch (This request is not authorized to perform this operation using this permission.)

Using the BC application source without modifications

I tried to go through the setup steps defined in [Installation and configuration](microsoft/bc2adls/blob/main/.assets/Setup.md.assets/Setup.md) and setup everything described there (maybe even a bit more):
- using account with only one user available, which is Global Admin obviously
![image](https://user-images.githubusercontent.com/17279234/185428308-3354d52e-8fe8-429c-8863-933f356a7933.png)
- registered an application bc2adls; specified and noted secret; specified redirect url that is in the instruction
![image](https://user-images.githubusercontent.com/17279234/185415241-59a2e41c-dee9-4220-b9ac-2adc01e3ac42.png)
- extra step - added Azure Storage.user_impersonation to the API permissions for the application
![image](https://user-images.githubusercontent.com/17279234/185416563-bd8f832b-cffc-4b63-9bf6-7a68141e1a46.png)
- created storage account 
![image](https://user-images.githubusercontent.com/17279234/185416871-23d11fe1-b277-4cda-9b4d-c9a07ca2f2e1.png)
- granted Storage Blob Data Contributor role + extra Storage Blob Data Owner, and Storage Blob Data Reader roles to the account (Contributor, Owner and User Access Administrator were initially)
![image](https://user-images.githubusercontent.com/17279234/185417191-e216795d-7c70-4ff6-9be0-a50762b20c8b.png)
- created new setup using the page Export to Azure Data Lake Storage in Business Central, specified desired container name bc2adlscont, tenant id, storage account name, generated client id and secret
![image](https://user-images.githubusercontent.com/17279234/185419668-f94b8817-6b47-49ee-9f48-ac7d99854a1f.png)

I assume now it should at least be able to create container and export file to the blob storage, but I get an error
![image](https://user-images.githubusercontent.com/17279234/185428919-c85cae9a-8bca-49aa-88d4-abb70c6ca2e7.png)

What do I miss in setups?

**Comment by DuttaSoumya** [comment]
Thanks for writing to us. The `ContainerExists` calls the `ADLSEHttp.InvokeRestApi` function. So please put a breakpoint on [this line](https://github.com/microsoft/bc2adls/blob/9350af07ce2d36217b39e605638ff2d0497aea75/businessCentral/src/ADLSEHttp.Codeunit.al#:~:text=Client.SetBaseAddress(Url)%3B), and then gather the URL, Headers that are used in the Http REST API call. (You may be required to uncomment the `[NonDebuggable]` attribute in the `AddAuthorization` function in the same codeunit.) Then try to see if you can make the same Https request through Postman / .NET console app and check if you are getting the same error.  

For your information, this is the call that is invoked from BC to ADLS: [Get Container Metadata](https://docs.microsoft.com/en-us/rest/api/storageservices/get-container-metadata).

**Comment by PaulFurlet** [comment]
Hi.
in the InvokeRestAPI `URL` is the following: `https://fpltest03.blob.core.windows.net/bc2adlscont?restype=container&comp=metadata`
in the `AddAuthorization` the function `AcquireTokenAOAuth2` is called, where:
`URI` is `https://login.microsoftonline.com/fafe0a34-[redacted, correct]/oauth2/token`
`RequestBody` is `resource=https%3A%2F%2Fstorage.azure.com%2F&scope=https%3A%2F%2Fstorage.azure.com%2Fuser_impersonation&client_id=b84a77ba-[redacted, correct]&client_secret=[redacted, correct]&client_info=1&grant_type=client_credentials`
as the result, `AccessToken` is obtained successfully
So, Headers look legit
`Authorization`: `Bearer [redacted, generated AccessToken]`
`x-ms-version`: `2020-10-02`
`x-ms-date`: `Thu, 18 Aug 2022 22:01:27 GMT`
but the result of Client.Get is the following:
> '<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.
> RequestId:128a8d2d-f01e-005d-554b-b3ea7a000000
> Time:2022-08-18T21:46:17.8032396Z</Message></Error>'

Postman returns the same:
![image](https://user-images.githubusercontent.com/17279234/185505511-07af20ea-0abe-46a8-92bd-5869c2d8df48.png)
![image](https://user-images.githubusercontent.com/17279234/185505577-81b2e22d-0af1-49ce-9bf9-4e5080f214c4.png)

**Comment by DuttaSoumya** [comment]
Dear @PaulFurlet,

The .NET code which makes a similar call fails using the Blob REST API- so this should be escalated as a support request to the Azure Data Lake team, as the authentication mechanism that you specify seems to be correct- and an error in authentication is out of scope for this project.

HOWEVER, it may be that the real cause is that you do not have the role Storage Blob Data Contributor assigned to your application **bc2adls**. From the screenshots I can see the role having been assigned to **p f <admin@fpltest01...>** but not to the **bc2adls** app registration. If you follow the [instructions](https://github.com/microsoft/bc2adls/blob/main/.assets/Setup.md#step-3-connect-credential-to-the-blob-storage) closely, the role Storage Blob Data Contributor is assigned to the app registration (see the setting 3), and not to any "real" AAD user.
![image](https://user-images.githubusercontent.com/38040179/185616359-217bcebd-cd93-4533-ac4c-e5e2056d714e.png)

Best regards,
The bc2adls team.

**Comment by PaulFurlet** [comment]
Hello @DuttaSoumya
Thank you for tour explanation, but I cannot select any application on assigning role.
I have only user or managed identity (I do not have any). So I selected and added the only available variant.
That's why I am wondering what could I miss that I cannot specify registered app as role executor for the storage account?
![image](https://user-images.githubusercontent.com/17279234/185765202-2b9f89c9-3e96-42a4-9bef-8fd2dfba6481.png)
![image](https://user-images.githubusercontent.com/17279234/185765209-3545ca0e-1492-40c4-a33e-4fcbcc7cff2a.png)

**Comment by DuttaSoumya** [comment]
Hi @PaulFurlet,

You should be able to see the App Registration name in the list for **Select members** when you have selected **Assign access to** as `User, group, or service principal`. Once selected, the **Access Control (IAM)** pane for the storage account should show something like this- note the **Type** is `App`, not `User`.
![image](https://user-images.githubusercontent.com/38040179/185949490-98542b98-e550-463c-8df5-613d3a97a086.png)

But is seems you are unable to see the App Registration as a user. I would urge you to please re-try **[Step 1. Create an Azure Service Principal](https://github.com/microsoft/bc2adls/blob/main/.assets/Setup.md#step-1-create-an-azure-service-principal)** or just do the tutorial [Register an application with Microsoft identity platform](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app) and then check if the newly registered application shows up as a user in the **Access Control (IAM)** pane. 

Best regards,
The bc2adls team.

**Comment by PaulFurlet** [comment]
Hi @DuttaSoumya,
Thank you for your hints. But I still do not see any clue of application in the list. There is Enterprise Application with my Application Id created automatically.
Assuming, even demo account should be able to perform setup, here are the steps I do for the new registration [I removed everything beforehand, this is demo account anyways, added new user storageacc with simple User permissions]
just like specified in the instructions:
1. Registering new application
![image](https://user-images.githubusercontent.com/17279234/185978013-00c99a24-680e-4cd7-8b6e-375840168fc4.png)
![image](https://user-images.githubusercontent.com/17279234/185978261-5741bc6a-8248-437e-97e9-b384aab05204.png)
3. creating Application Secret 
![image](https://user-images.githubusercontent.com/17279234/185978089-a81225de-f8df-4b99-a383-4965f84cd6dd.png)
4. {not described in instructions} adding Azure Storage user_impersonation to API permissions
![image](https://user-images.githubusercontent.com/17279234/185978215-96508f70-58b1-4400-890e-96f6c56e13fb.png)
5. new Enterprise Application created automatically, no manual provisioning applied
![image](https://user-images.githubusercontent.com/17279234/185978534-0b73a384-91c7-41a4-9cd0-1dbe04f9de1f.png)
6. new Resource Group (I removed all other)
![image](https://user-images.githubusercontent.com/17279234/185978897-8b471b48-cb1c-47a0-a453-dea8d8bc0f56.png)
7. new Storage Account
![image](https://user-images.githubusercontent.com/17279234/185979102-b93521e2-2a32-4534-ba7a-5a960a1fe214.png)
8. enabled hierarchical namespace
![image](https://user-images.githubusercontent.com/17279234/185979170-9f29461e-1ec1-40d5-be50-187d2d3c9986.png)
9. trying to add role assignment for the Storage Account - no luck to see any app in the list
![image](https://user-images.githubusercontent.com/17279234/185979279-5b19967a-26d1-4c7d-b55b-49bd26ca1b82.png)

**Comment by PaulFurlet** [comment]
@DuttaSoumya omg... if I start to type in the app name, it appears... so unobvious...
![image](https://user-images.githubusercontent.com/17279234/185980223-49553a63-6e52-497e-96ce-fb9ac732e000.png)
checking sthuff further...

**Comment by PaulFurlet** [comment]
It worked and I can continue further.
Thank you!
