### ISSUE TITLE
Adding more fields in BC tables exporting via extension after the initial load

### ISSUE THREAD

**Issue by Swetha8587** [microsoft/bc2adls#36]
Hi Team,

We have been trying the below project for one of our projects. It is an excellent solution for the data export from Business Central. 

[GitHub - microsoft/bc2adls: Exporting data from Dynamics 365 Business Central to Azure data lake storage](https://github.com/microsoft/bc2adls)

My question is regarding - Scenario - If we export a set of fields and in some tables and make the data available in the final Data folder. In the future (maybe in the next couple of months) if there is any new reporting requirement for which we need to add more fields to some tables. 

Can you suggest or confirm that the below is correct

The process for that is to add more fields into tables in BC extension and run the job then subsequently run the pipelines to get the data into the Data folder? Would the history data also be added to the data?

I imagine this is a generic scenario in any project.

Hope the above makes sense. Please let me know if you have any questions.

Any suggestions on any other solution to this scenario would be appreciated.

**Comment by DuttaSoumya** [comment]
Hello @Swetha8587,

If at a later point in your project, you have to add the fields you could try out the following approaches,
•	Export all the data again with the new schema and then consolidate into the data folder
•	Alternatively, if you do not have the data exported previously in your BC anymore, you will have to “consolidate” the data from the two schemas yourself. This could be done using your own custom built Synapse pipeline that takes the old **data** and the new **data** folders, fills in the “right” values for the new fields that are to be added on the old data and consolidates the two, finally writing everything to the new **data** folder. Take inspiration of how to create such a pipeline from the one that is already a part of the offer [here](https://github.com/microsoft/bc2adls/tree/main/synapse).

Best regards,
The bc2adls team.
