### ISSUE TITLE
Parquet file not making use of the original Data Type of the columns

### ISSUE THREAD

**Issue by eclipses** [microsoft/bc2adls#38]
All columns different of Data Type String (e.g. Decimal Date, DateTime, Int, Boolean) are exported in parquet file as BYTE_ARRAY.

Parquet file should maintain the original Data Type of each column.

**Comment by DuttaSoumya** [comment]
Hi Sergio,

could you please elaborate where you see this? If you create an Azure Synapse Serverless SQL on top of an entity of the CSV, it seems that the data types are respected.

Best regards.

**Comment by eclipses** [comment]
Hi Soumya, 

I've sent you a file via email. 

You can test this with any table, you need to select to generate Parquet files. Take in consideration for example standard field that should be DateTime, they are exported ad strings:

|-- timestamp-0: string (nullable = true)
|-- SystemCreatedAt-2000000001: string (nullable = true)
|-- SystemModifiedAt-2000000003: string (nullable = true)

This is happening for all data types.

**Comment by DuttaSoumya** [comment]
Hi @eclipses ,

I just wanted to touch base if you have been able to solve the issue. In the meeting we had last time, we saw that the data types was respected in the parquet format. So we would like to close the issue.

Best regards,
Dutta.
