### ISSUE TITLE
Form.RunModal Error when picking fields for Tables

### ISSUE THREAD

**Issue by coffeedave** [microsoft/bc2adls#44]
I've compiled and uploaded the app to one of our BC test environments. It connects fine but when clicking to try and add columns:

![image](https://user-images.githubusercontent.com/9153639/192755478-a0f9cadc-e66a-40b9-8c28-30366dd67784.png)

It's returning the following error:

```
The following AL methods are limited during write transactions because one or more tables will be locked:

Form.RunModal is not allowed in write transactions.

Codeunit.Run is allowed in write transactions only if the return value is not used. For example, 'OK := Codeunit.Run()' is not allowed.

Report.RunModal is allowed in write transactions only if 'RequestForm = false'. For example, 'Report.RunModal(...,false)' is allowed.`

```

![image](https://user-images.githubusercontent.com/9153639/192738319-1a10c412-6f59-4204-8e30-8f0051dc2a52.png)

Settings appear fine as it's able to connect to ADLS using the account's etc.  Any idea of next steps to troubleshoot/fix or is there something obvious I might have missed in setting it up?

**Comment by DuttaSoumya** [comment]
Thank you @coffeedave for pointing this out. This was indeed a bug introduced. The fix is [merged](https://github.com/microsoft/bc2adls/pull/48) into the main branch. Kindly get the latest from there.
