### ISSUE TITLE
Missing Step in Documentation

### ISSUE THREAD

**Issue by JulianSchmidtke** [microsoft/bc2adls#62]
Hi,

I'm new to Datalake and Synaps Pipelines und trying to create the example workflow.

When i create the Datasets it asks me for the source and the format of my data.
![image](https://user-images.githubusercontent.com/22668495/203087148-0bb6a555-a3a7-4485-b8d5-6169208eed3a.png)
![image](https://user-images.githubusercontent.com/22668495/203087178-2ae3ac96-1950-448b-864b-750702bf26c9.png)

I initially used JSON and now receive the following error when triggering Consolidation_AllEntities:

```
Operation on target Entities failed: Failure happened on 'Source' side. ErrorCode=JsonInvalidDataFormat,'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Error occurred when deserializing source JSON file 'deltas/Customer-18/A342654A-F53B-46C0-99D8-6942A6153F18.csv'. Check if the data is in valid JSON object format.,Source=Microsoft.DataTransfer.Common,''Type=Newtonsoft.Json.JsonReaderException,Message=Error parsing NaN value. Path '', line 1, position 1.,Source=Newtonsoft.Json,'
```

I then tried to change the entity datasource to csv format, but now receive the following error:
![image](https://user-images.githubusercontent.com/22668495/203087805-da1b4655-3f2f-438c-ab5d-213917add4fe.png)

Where might be my mistake? Thank you in advance!

**Comment by Bertverbeek4PS** [comment]
@JulianSchmidtke in the documentation
https://github.com/microsoft/bc2adls/blob/main/.assets/Setup.md#step-6-create-data-integration-pipelines

There you can download and import the templates. Import in the right order and you can use it.

**Comment by JulianSchmidtke** [comment]
Hey @Bertverbeek4PS  thank you for the answer. I'll try again but I'm still thinking a step is missing in the docs. 

What Format do i have to use? It only says + -> Integration Dataset but not what Type it is

**Comment by Bertverbeek4PS** [comment]
@JulianSchmidtke if you import these datasets and pipelines in this order:
![image](https://user-images.githubusercontent.com/71499421/203248524-e43c1aa2-931b-42d0-95c6-3a81f6c145ee.png)
Then you don't have to choose something.

**Comment by JulianSchmidtke** [comment]
@Bertverbeek4PS  I'm sorry for my ignorance but what do i do wrong here? i always have to choose something.

https://user-images.githubusercontent.com/22668495/203259978-6a1db57b-86df-4d8a-827d-4eef77c46f80.mp4

**Comment by JulianSchmidtke** [comment]
I found out: I can create a Datset as json ans when i import it the type is automatically changed.
