### ISSUE TITLE
Add additional cdm Properties

### ISSUE THREAD

**Issue by JulianSchmidtke** [microsoft/bc2adls#68]
CDM has some properties that should be checked for business central.

https://learn.microsoft.com/en-us/common-data-model/1.0om/api-reference/cdm/typeattribute

Name | Type | Description
-- | -- | --
DataType | CdmDataTypeReference | The type attribute's data type, a Common Data Model object reference.
DataFormat | CdmDataFormat | The type attribute's data format (string, int, etc.).
AttributeContext | CdmAttributeContextReference | The attribute context of the type attribute.
DefaultValue | dynamic | The type attribute's default value.
Description | string | The type attribute's description.
DisplayName | string | The type attribute's display name.
SourceName | string | The type attribute's source name.
IsNullable | bool? | Denotes whether the type attribute can be null or not.
IsPrimaryKey | bool? | Denotes whether the type attribute is the primary key.
IsReadOnly | bool? | Denotes whether the type attribute is read only.
MaximumLength | int? | The type attribute's maximum length.
MaximumValue | string | The type attribute's maximum value (for data types that this can apply to, like integers).
MinimumValue | string | The type attribute's minimum value (for data types that this can apply to, like integers).
SourceOrdering | int? | Denotes the order attributes exist in some underlying source system.
ValueConstrainedToList | bool? | Denotes whether the type attribute's value is constrained to a list. The values can only be from enums.

I believe the following should be included in BC exports:

Name | In BC
-- | -- 
DefaultValue  | InitValue
Description | Description
IsNullable  | not NotBlank
IsPrimaryKey | Part of Primary Key
MaximumLength | Length of Code/Text Fields e.g. [20]
MaximumValue | MaxValue
MinimumValue | MinValue

The following two might also be possible:

Name | In BC
-- | -- 
SourceOrdering | Maybe the Enum Value IDs
ValueConstrainedToList | If Type is Option or Enum

Feel free to discuss or add additional properties

**Comment by DuttaSoumya** [comment]
Great point @JulianSchmidtke! we started off with the bare minimum definitions to give meaningful insights. But we will certainly look at the list of properties you painstakingly compiled here, as and when the requirements occur. 

We have not come across any case when the data in the lake would be _edited_, which is typically when you would want to enforce these constraints on incoming data. That's why it has not been a priority for us to add these properties.
