### ISSUE TITLE
BC Export Errors

### ISSUE THREAD

**Issue by tglink72** [microsoft/bc2adls#73]
Hello,

      Hope all is well. We have begun to seem some consistent export errors in the BC extension. Below and attached are examples of the errors we are receiving. We  are able to then manually run the process without error. The issue does not look to be consistent as to the table that is failing or the amount of data being sent. Have any other people seen this type of ongoing errors with the export from BC? Is there anything we can do to tune or configure the tool to see more consistent success in exports?

The operation was canceled."ADLSE HttpSSI"(CodeUnit 66059).InvokeRestApi - BC2ADLS by Stoneridge Software, LLC\"ADLSE HttpSSI"(CodeUnit 66059).InvokeRestApi line 4 - BC2ADLS by Stoneridge Software, LLC\"ADLSE Gen 2 UtilSSI"(CodeUnit 66058).AddBlockToDataBlob line 11 - BC2ADLS by Stoneridge Software, LLC\"ADLSE CommunicationSSI"(CodeUnit 66054).FlushPayload line 16 - BC2ADLS by Stoneridge Software, LLC\"ADLSE CommunicationSSI"(CodeUnit 66054).Finish line 2 - BC2ADLS by Stoneridge Software, LLC\"ADLSE CommunicationSSI"(CodeUnit 66054).TryFinish line 2 - BC2ADLS by Stoneridge Software, LLC\"ADLSE ExecuteSSI"(CodeUnit 66056).ExportTableUpdates line 29 - BC2ADLS by Stoneridge Software, LLC\"ADLSE ExecuteSSI"(CodeUnit 66056).TryExportTableData line 12 - BC2ADLS by Stoneridge Software, LLC\"ADLSE ExecuteSSI"(CodeUnit 66056).OnRun(Trigger) line 46 - BC2ADLS by Stoneridge Software, LLC\"ADLSE ExecuteSSI"(CodeUnit 66056).ExportTableUpdates line 32 - BC2ADLS by Stoneridge Software, LLC\"ADLSE ExecuteSSI"(CodeUnit 66056).TryExportTableData line 12 - BC2ADLS by Stoneridge Software, LLC\"ADLSE ExecuteSSI"(CodeUnit 66056).OnRun(Trigger) line 46 - BC2ADLS by Stoneridge Software, LLC\

Thanks

Tom Link 

![BCExportError](https://user-images.githubusercontent.com/106773201/207400381-74e36815-dd16-4eac-8479-7bcfc259cec4.jpg)

**Comment by DuttaSoumya** [comment]
We are still curious @tglink72 about the issue and its reproducibility. Could you delve further into it based on my last message?

**Comment by tglink72** [comment]
Soumya,

               Thanks for the reply. We have initiated an automatic retry on failure that has helped to keep the export more reliable, though it does not solve the underlying issue. This customer is unique as they had performance issues when we were using change tracking and the deltas, so we modified the code to send all records each time. My concern is sending this much data daily is causing some of the inconsistent issues we have seen with processing.
We are working on implementing the latest version of the code in our Sandbox environments. Per your comment here https://github.com/microsoft/bc2adls/pull/55 , this version can pull from replicated data. Are there any configuration changes we have to make specific to this version to use a replicated database? I am not seeing any options in the Azure Export window that identifies whether to use transactional or replicated data.

Thanks again for your reply and for all of your work on this project!

Tom Link

**Comment by tglink72** [comment]
Soumya,

               Hello. One things we are seeing with the current export is that certain tables are reporting success in the export to ADL, but are not fully exporting. For example the Customer-18 table is reporting success in the export window, but only exporting a fraction of the total records from the table. A full Customer export should be several hundred MB, but we are seeing that it is only exporting less than a MB and then reporting success. Have you seen this issue in the past?

Thanks

Tom

***@***.***

**Comment by tglink72** [comment]
Soumya,

               Hope all is well. The issue below is becoming more consistent. Several tables (Customer, SalesInvoiceLine) report success in the export from BC, yet are only exporting a fraction of the records for the table, rather than the full table after reset. Have you seen this in other instances of the export tool?  Thanks for any help.

Tom Link

From: Tom Link ***@***.***>
Sent: Thursday, January 12, 2023 8:14 AM
To: microsoft/bc2adls ***@***.***>; microsoft/bc2adls ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [microsoft/bc2adls] BC Export Errors (Issue #73)

Soumya,

               Hello. One things we are seeing with the current export is that certain tables are reporting success in the export to ADL, but are not fully exporting. For example the Customer-18 table is reporting success in the export window, but only exporting a fraction of the total records from the table. A full Customer export should be several hundred MB, but we are seeing that it is only exporting less than a MB and then reporting success. Have you seen this issue in the past?

Thanks

Tom

***@***.***

**Comment by DuttaSoumya** [comment]
First of all, as you also shared @tglink72, it is not a best practice to repeatedly export all data from all tables. bc2adls is meant to be run with incremental changes being exported.

Note that in order to export data, bc2adls spawns a new session for every table for every company (when relevant) So depending on the data you are exporting this could be too many! After all, BC runs within the bounds of [certain operation limits](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/operational-limits-online).

if it is absolutely essential to export all data from a table, please identify such tables and only reset _those_ instead of _all_ tables. You may be able to implement that using [the API page](https://github.com/microsoft/bc2adls/blob/main/businessCentral/src/ADLSETableAPI.Page.al) that has been created. 

As the initial issue about the displayed error is not recurring, I am closing the current case. Please open a new one if relevant.
