### ISSUE TITLE
Write Transactions in Try Functions

### ISSUE THREAD

**Issue by thomas-tarp** [microsoft/bc2adls#81]
Hi 👋

Thank you for this great extension. It seems very useful.

I have been setting up this extension for a customer on a BC 21.2 OnPrem installation, and in doing so a question has arised.

**Observed behavior**
I have encountered that there are write transactions inside try functions.

The one I have encountered is found in table 82564 "ADLSE Table Last Timestamp" here:
![image](https://user-images.githubusercontent.com/44906913/211531862-fb96e7fc-8180-452f-8dd6-034bb6896d61.png)

This causes a runtime error when write transactions in try functions are disabled (server configuration key "DisableWriteInsideTryFunctions" = true).

Thus, I have had to disable this configuration to make the export work.

The default configuration is to disable write transactions in try functions because changes are not rolled back as outlined in the documentation here:
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-handling-errors-using-try-methods

I have not worked much with cloud implementations, but I assume this is also default behavior in cloud.

However, the procedure names suggest that this is intentional behavior.

**Question**
I would prefer to use the default configuration to avoid any issues elsewhere in the application.

Therefore, my question is if this is indeed intentional, and if there is good reasoning behind it?
And if not, would there be support for refactoring this to not have write transactions in try functions?

**Comment by DuttaSoumya** [comment]
Thanks for pointing this out @thomas-tarp. As you can see, we are considering the above fix for the issue.

**Comment by thomas-tarp** [comment]
Great, thank you. This change should definitely solve the issue for me.
