### ISSUE TITLE
API ADLSERun-82566 Table

### ISSUE THREAD

**Issue by bbonekamp** [microsoft/bc2adls#83]
It would be helpful to be able to extract ADLSERun-82566 Table via Web Services (and the standard Power BI Business Central adapter) in order to build e.g. monitoring dashboards.

A similar API is already available for the ADLSETables-82561. However, this only holds the latest status.

**Comment by DuttaSoumya** [comment]
Hi @bbonekamp,

We have always invited contributions from the community- it should be easy to create an API page similar to [ADLSETableApi.Page.al](https://github.com/microsoft/bc2adls/blob/main/businessCentral/src/ADLSETableAPI.Page.al) for this table in a pull request that we could then review.

You may use the new and shiny [API query generator tool](https://github.com/microsoft/BCTech/tree/master/samples/APIQueryGenerator) to create these as well!

Best regards,
Dutta.
