### ISSUE TITLE
Exports with different frequencies

### ISSUE THREAD

**Issue by thomas-tarp** [microsoft/bc2adls#87]
Hi,

I have a suggestion for a change to the extension.
It changes the export structurally so I would like to discuss and know if there is support for it.

There might also be workarounds or alternative implementations of the intended feature that I have not considered.

**Requested Feature**
The customer I am working with would like to be able to export various data (tables) with different frequencies.
The rationale is that some data is needed closer to real-time than other data.

**Observed Behavior**
Currently, the scheduling functionality is bound to an "ADLSE Setup" record where "ADLSE Table" records are lines to to the "ADLSE Setup"-"header", so to speak.

"ADLSE Setup" is implemented following the singleton pattern.
I assume that the rationale behind the singleton implementation is that you want all setup fields on the "ADLSE Setup" record to be the same for all exports, which makes sense.

**Suggested Behavior**
My immediate idea is to separate the scheduling functionality from the "ADLSE Setup" record and instead introduce a new header entity for exports.

This would make it possible to gather various tables in a collection that can be setup with appropriate configurations, i.e. scheduling in my case.
I also think this would make sense for potential features in the future. One that comes to mind would be the ability to filter the tables that are exported.

**Discussion**
First of all, it is sensible to consider if it is even relevant to have separate exports with different scheduling configurations.
For example, one might argue that you could just use the highest frequency as the common denominator.
However, that would be based on the assumption that if the data is needed less frequently, it probably also does not change frequently. I believe this will not always be the case.

Secondly, I am not sure if this change would have significant ramifications elsewhere, e.g. for the pipelines or the export itself. I would not think so, but I am not sure.

Let me know what you think.

Best regards!

**Comment by DuttaSoumya** [comment]
Very good points @thomas-tarp. Would you be interested to cover these points on an online meeting? Kindly write directly to bc2adls@microsoft.com so we can setup one and discuss your idea further.

**Comment by Bertverbeek4PS** [comment]
@thomas-tarp that is indeed a very nice feature! More customers want this!

**Comment by thomas-tarp** [comment]
Thank you as well for the meeting today.

I will test with differentiated frequencies on the Synapse pipelines. It looks like this should fulfill the needs.

I'm closing the issue.
